# Main analysis options for all FBS dart packages to inherit from

include: package:flutter_lints/flutter.yaml

analyzer:
  language:
    strict-casts: true
    strict-raw-types: true
    strict-inference: true

  # Things we really want to enforce in our code
  errors:
    avoid_js_rounded_ints: error
    always_declare_return_types: error
    always_use_package_imports: error
    avoid_relative_lib_imports: error
    avoid_unused_constructor_parameters: error
    inference_failure_on_function_invocation: error
    missing_default_value_for_parameter: error
    parameter_assignments: error
    prefer_final_fields: error
    prefer_final_locals: error
    prefer_final_in_for_each: error
    require_trailing_commas: error
    sort_child_properties_last: error
    sort_constructors_first: error
    sort_unnamed_constructors_first: error
    use_named_constants: error
    use_build_context_synchronously: error
    body_might_complete_normally_nullable: ignore
    unnecessary_breaks: warning
    avoid_void_async: error
    flutter_style_todos: warning
    prefer_const_constructors: warning
    prefer_const_declarations: warning
    prefer_const_constructors_in_immutables: warning
    depend_on_referenced_packages: warning

linter:
  rules:
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    always_use_package_imports: true
    avoid_annotating_with_dynamic: false # it's ok to be extra explicit
    avoid_bool_literals_in_conditional_expressions: false
    avoid_catches_without_on_clauses: false
    avoid_classes_with_only_static_members: false
    avoid_dynamic_calls: true
    avoid_js_rounded_ints: true
    dangling_library_doc_comments: false
    flutter_style_todos: true
    no_leading_underscores_for_local_identifiers: false
    omit_local_variable_types: true
    prefer_single_quotes: true
    unawaited_futures: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    parameter_assignments: true
    unnecessary_breaks: true
    sort_constructors_first: true
    avoid_void_async: true
    prefer_const_constructors: true
    prefer_const_declarations: true

formatter:
  page_width: 100
  trailing_commas: preserve
